# https://github.com/marketplace/actions/hub-mirror-action
on:
  # push:
  # 加入其方便进行推送仓库
  # 每天早上十点更新仓库
  schedule:
    - cron: '0 2 * * *'
    - cron: '0 13 * * *'
name: Update gitee
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - name: Get repository list exclude private and fork
      id: repo
      uses: yi-Xu-0100/repo-list-generator@v1.0.1
    - name: Mirror the Github repos to Gitee.
      uses: Yikun/hub-mirror-action@master
      with:
        src: github/ZHYCarge
        dst: gitee/zhycarge
        dst_key: ${{ secrets.GITEE_PRIVATE_KEY }}
        dst_token:  ${{ secrets.GITEE_TOKEN }}
        #static_list: 'test'
        black_list: 'actions,photo,ZHYCarge.github.io,notes,SundryBox'
        static_list: ${{ steps.repo.outputs.repoList }}
        #white_list: ''
        force_update: false
        debug: false
